flexbackend.site/Controllers/DIscountController.cs
using Discount.dll.Models.Dtos;
using Discount.dll.Models.Infra.DapperRepositories;
using Discount.dll.Models.Infra.EFRepositories;
using Discount.dll.Models.Interfaces;
using Discount.dll.Models.Services;
using Discount.dll.Models.ViewModels;
using EFModels.EFModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace flexbackend.site.Controllers
{
	public class DiscountController : Controller
	{
		private IDiscountRepository _repo;
		private DiscountService _service;
		public DiscountController()
		{
			_repo = new DiscountEFRepository();
			_service = new DiscountService(_repo);
		}

		// GET: Discount
		public ActionResult Index(bool searchExpired = false, string searchDiscountName = null)
		{
			ViewBag.searchExpired = searchExpired;
			ViewBag.searchDiscountName = searchDiscountName;

			return View();
		}
		[HttpPost]
		public ActionResult GetDatas(bool searchExpired = false, string searchDiscountName = null)
		{
			return Json(GetDiscounts(searchExpired, searchDiscountName));
		}

		public IEnumerable<DiscountIndexVM> GetDiscounts(bool searchExpired = false, string searchDiscountName = null)
		{
			return _service.GetDiscounts(searchExpired, searchDiscountName).Select(x => x.ToIndexVM());
		}
		public ActionResult CreateOrEdit(int? id)
		{
			List<SelectListItem> projectTagitems = new List<SelectListItem>();
			var db = new AppDbContext();
			projectTagitems.AddRange(db.ProjectTags.Where(p => p.Status == true)
							.Select(p => new SelectListItem { Value = p.ProjectTagId.ToString(), Text = p.ProjectTagName }));

			List<SelectListItem> discountType = new List<SelectListItem>
			{
				new SelectListItem { Value = "0" , Text = "金額" },
				new SelectListItem { Value = "1" , Text = "百分比" },
			};

			List<SelectListItem> conditionType = new List<SelectListItem>
			{
				new SelectListItem { Value = "0" , Text = "依照購買價格" },
				new SelectListItem { Value = "1" , Text = "依照商品件數" },
			};

			ViewBag.ConditionType = conditionType;
			ViewBag.DiscountType = discountType;
			if (id == null || id.Value == 0)
			{
				ViewBag.projectTagitems = new SelectList(projectTagitems, "Value", "Text", null);
				DiscountCreateOrEditVM vm = new DiscountCreateOrEditVM
				{
					DiscountId = 0,
					DiscountName = null,
					DiscountDescription = null,
					ProjectTagId = null,
					ConditionType = 0,
					ConditionValue = 0,
					DiscountType = 0,
					DiscountValue = 0,
					StartDate = DateTime.Today,
					EndDate = null,
					OrderBy = null
				};

				return View(vm);
			}
			else
			{
				DiscountCreateOrEditVM vm = _service.GetDiscountById(id.Value).ToCreateOrEditVM();
				IProjectTagRepository repo = new ProjectTagDapperRepository();
				ProjectTagService service = new ProjectTagService(repo);

				var projectTag = service.GetProjectTag(vm.ProjectTagId);
				if (projectTag != null && projectTag.Status == false)
				{
					projectTagitems.Add(new SelectListItem { Value = vm.ProjectTagId.ToString(), Text = vm.ProjectTagName });
				}

				ViewBag.projectTagitems = new SelectList(projectTagitems, "Value", "Text", vm.ProjectTagId);
				return View(vm);
			}
		}
		[HttpPost]
		public ActionResult CreateOrEdit(DiscountCreateOrEditVM vm)
		{
			if (vm.DiscountId == 0)
			{
				if (ModelState.IsValid)
				{
					var result = _service.Create(vm.ToDto());
					return Json(result.result);
				}
			}
			else
			{
				if (ModelState.IsValid)
				{
					return Json(_service.Update(vm.ToDto()));
				}
			}
			return Json("");
		}

		[HttpDelete]
		public ActionResult Delete(int id)
		{
			int[] ids = new int[1];
			ids[0] = id;
			_service.Delete(ids);
			return Content("Resource deleted successfully.");
		}

	}
}

flexbackend.site/Views/DIscount/CreateOrEdit.cshtml
@model Discount.dll.Models.ViewModels.DiscountCreateOrEditVM

@{
    ViewBag.Title = "折扣管理";
    SelectList projectTagitems = ViewBag.projectTagitems as SelectList;
    SelectList discountType = ViewBag.DiscountType as SelectList;
    SelectList conditionType = ViewBag.ConditionType as SelectList;
}

<div class="d-flex justify-content-between align-items-end">
    <h2>折扣管理</h2>
    <div>
        @Html.ActionLink("回折扣首頁", "Index", null, new { @class = "fs-5" })
    </div>
</div>


@using (Html.BeginForm("CreateOrEdit", "Discount", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DiscountId)
        <div class="border border-2 border-dark p-0">
            <div class="text-bg-dark py-2 px-4 fs-5">基本設定</div>
            <div class="row row-cols-2 p-4">
                <div class="mb-3">
                    @Html.LabelFor(model => model.DiscountName, htmlAttributes: new { @class = "form-label" })
                    @Html.EditorFor(model => model.DiscountName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiscountName, "", new { @class = "text-danger" })
                </div>

                <div class="mb-3">
                    @Html.LabelFor(model => model.DiscountDescription, htmlAttributes: new { @class = "form-label" })
                    @Html.EditorFor(model => model.DiscountDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiscountDescription, "", new { @class = "text-danger" })
                </div>

                <div class="mb-3">
                    @Html.LabelFor(model => model.ProjectTagId, htmlAttributes: new { @class = "form-label" })
                    @Html.DropDownList("ProjectTagId", projectTagitems, "全部商品", new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.ProjectTagId, "", new { @class = "text-danger" })
                </div>
                <div class="mb-3">
                    @Html.LabelFor(model => model.OrderBy, htmlAttributes: new { @class = "form-label" })
                    @Html.EditorFor(model => model.OrderBy, new { htmlAttributes = new { @class = "form-control", type = "number", min = 0 } })
                    @Html.ValidationMessageFor(model => model.OrderBy, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="border border-2 border-dark p-0">
            <div class="text-bg-dark py-2 px-4 fs-5">折扣條件設定</div>
            <div class="row row-cols-2 p-4">
                <div class="mb-3">
                    @Html.LabelFor(model => model.ConditionType, htmlAttributes: new { @class = "form-label" })
                    @Html.DropDownListFor(model => model.ConditionType, conditionType, new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.ConditionType, "", new { @class = "text-danger" })
                </div>

                <div class="mb-3">
                    @Html.LabelFor(model => model.ConditionValue, htmlAttributes: new { @class = "form-label" })
                    @Html.EditorFor(model => model.ConditionValue, new { htmlAttributes = new { @class = "form-control", type = "number", min = 0 } })
                    @Html.ValidationMessageFor(model => model.ConditionValue, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="border border-2 border-dark p-0">
            <div class="text-bg-dark py-2 px-4 fs-5">優惠設定</div>
            <div class="row row-cols-2 p-4">
                <div class="mb-3">
                    @Html.LabelFor(model => model.DiscountType, htmlAttributes: new { @class = "form-label" })
                    @Html.DropDownListFor(model => model.DiscountType, discountType, new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.DiscountType, "", new { @class = "text-danger" })
                </div>

                <div class="mb-3">
                    @Html.LabelFor(model => model.DiscountValue, htmlAttributes: new { @class = "form-label" })
                    @Html.EditorFor(model => model.DiscountValue, new { htmlAttributes = new { @class = "form-control", type = "number", min = 0 } })
                    @Html.ValidationMessageFor(model => model.DiscountValue, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="border border-2 border-dark p-0">
            <div class="text-bg-dark py-2 px-4 fs-5">時間設定</div>
            <div class="row row-cols-2 p-4">
                <div class="mb-3">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "form-label" })
                    <input type="text" class="form-control" name="startDate" id="startDate" value="@(Model.StartDate.ToString("yyyy'/'MM'/'dd"))">
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>

                <div class="mb-3">
                    @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "form-label" })
                    <input type="text" class="form-control" name="endDate" id="endDate" value="@(Model.EndDate.HasValue?Model.EndDate.Value.ToString("yyyy'/'MM'/'dd"):"")">
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>




        <div class="my-3">
            <input type="submit" value="儲存" class="btn btn-primary" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $("#endDate").datepicker({ dateFormat: 'yy/mm/dd' });
            $("#startDate").datepicker({ dateFormat: 'yy/mm/dd' });

            var form = $("form");

            form.on("submit", handleSubmit);

            function handleSubmit(event) {
                event.preventDefault();
                var formData = $(this).serialize();

                $.ajax({
                    url: "/Discount/CreateOrEdit",
                    type: "POST",
                    data: formData
                }).done(data => {
                    if (data.IsSuccess) {
                        alert("提交成功！");
                        window.location.href = "/Discount/Index";
                    }
                    else if (data.ErrorMessage == undefined) {
                        return;
                    }
                    else {
                        alert(data.ErrorMessage);
                    }
                }).fail(err => {
                    console.log(err.statusText);
                });
            }
        })
    </script>
}

flexbackend.site/Views/DIscount/Index.cshtml
@{
    ViewBag.Title = "折扣管理";
}
@section Styles{
    <link href="~/lib/datatables/css/jquery.datatables.min.css" rel="stylesheet" />
}
<h2>折扣管理</h2>

<div class="search-bar-container mb-4 d-flex">
    <div class="left w-75 d-flex justify-content-start me-auto">
        <div class="w-25">
            <div class="input-group d-flex">
                <input class="form-control search-bar" type="text" placeholder="以折扣名稱搜尋...">
            </div>
        </div>
        <div><a href="javascript:;" id="clear-input">清空</a></div>
        <span>
            <label class="form-check-label get-complete" for="get-complete-checkbox">
                <input type="checkbox" class="form-check-input get-complete" id="get-complete-checkbox" />
                搜尋已過期折扣
            </label>
        </span>
    </div>

    <div class="right">
        <a href="@Url.Action("CreateOrEdit")" class="btn btn-primary">
            <i class="bi bi-plus-lg"></i> 新增
        </a>
    </div>
</div>
<table class="w-100 d-table">
    <thead>
        <tr>
            <th class="th-col-1">
                折扣名稱
            </th>
            <th class="th-col-1">
                折扣描述
            </th>
            <th class="th-col-1">
                對應商品
            </th>
            <th class="th-col-1">
                優惠條件
            </th>
            <th class="th-col-1">
                折扣方式
            </th>
            <th class="th-col-1">
                開始時間
            </th>
            <th class="th-col-1">
                結束時間
            </th>
            <th class="th-col-1">
                狀態
            </th>
            <th class="th-col-1">
                優先度
            </th>
            <th class="text-center">管理</th>
        </tr>
    </thead>
</table>
@section Scripts{
    <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
    <script>
        $(function () {


            const searchBar = $(".search-bar");
            const searchExpiredInput = $("#get-complete-checkbox");
            getDatas();
            function getDatas() {
                $(".d-table").DataTable({
                    ajax: {
                        type: "POST",
                        url: `/Discount/GetDatas`,
                        data: {
                            searchExpired: searchExpiredInput.prop("checked"),
                            searchDiscountName: searchBar.val()
                        },
                        dataSrc: function (data) {
                            return data;
                        },
                    },
                    columns: [
                        {
                            data: "DiscountName"
                        },
                        {
                            data: "DiscountDescription",
                            orderable: false
                        },
                        {
                            data: "ProjectTagNameToShow"
                        },
                        {
                            data: "ConditionValueStr",
                            orderable: false
                        },
                        {
                            data: "DiscountValueStr",
                            orderable: false
                        },
                        {
                            data: "StartDateStr",
                            "width": "15%"
                        },
                        {
                            data: "EndDateStr",
                            "width": "15%"
                        },
                        {
                            data: null,
                            render: function (data) {
                                return `<div class="text-center ${data.Status == "進行中" ? "status-success" : (data.Status == "已過期" ? "status-dark" : "status-primary")}" >
                                                ${data.Status}</div >`;
                            }
                        },
                        {
                            data: null,
                            render: function (data) {
                                return `<div class="text-end">${data.OrderByStr}</div>`;
                            }
                        },
                        {
                            data: null,
                            render: function (data) {
                                if (data.Status == "已過期") {
                                    return `<div class="manage-btn-container d-flex justify-content-around">
                                                    <a href="#" class="btn-del" data-id="${data.DiscountId}" data-name="${data.DiscountName}"><i class="bi bi-trash-fill"></i></a>
                                                </div>`;
                                }
                                return `<div class="manage-btn-container d-flex">
                                            <a href="#" class="btn-edit me-1" data-id="${data.DiscountId}"><i class="bi bi-pencil-square"></i></a>
                                            <a href="#" class="btn-del" data-id="${data.DiscountId}" data-name="${data.DiscountName}"><i class="bi bi-trash-fill"></i></a>
                                        </div>`;
                            },
                            orderable: false
                        }
                    ]
                    ,
                    order: [
                        [7, "desc"],
                        [8, "asc"]

                    ],
                    language: {
                        paginate: {
                            previous: '<i class="bi bi-chevron-left"></i>',
                            next: '<i class="bi bi-chevron-right"></i>'
                        },
                        info: "第 _START_ 到 _END_ 筆，總共 _TOTAL_ 筆",
                    },
                    dom: '1Brtip',
                    columnDefs: [
                        { targets: [3, 4], className: 'text-right align-right' }
                    ]
                });
            }
            $(document).on("click", ".btn-edit", function () {
                editDiscount($(this).data("id"));
            });
            function editDiscount(discountId) {
                $.ajax({
                    url: '/Discount/CreateOrEdit?id=' + discountId,
                    type: 'GET',
                    success: function (response) {
                        window.location.href = '/Discount/CreateOrEdit?id=' + discountId;
                    },
                    error: function (xhr, status, error) {
                    }
                });
            }

            $(document).on("click", ".btn-del", function () {
                showDeleteConfirmation($(this).data("id"), $(this).data("name"));
            });

            function showDeleteConfirmation(discountId, name) {
                var confirmed = confirm(`是否確定刪除，優惠 ${name} ?`);
                if (confirmed) {
                    deleteDiscount(discountId);
                }
            }

            function deleteDiscount(discountId) {
                $.ajax({
                    url: '/Discount/Delete/' + discountId,
                    type: 'DELETE',
                    success: function (response) {
                        alert("刪除資料成功.");
                        $(".d-table").DataTable().destroy();
                        getDatas();
                    },
                    error: function (xhr, status, error) {
                        console.log(xhr.responseText);
                        alert("Failed to delete resource.");
                    }
                });
            }

            $("#get-complete-checkbox").click(function () {
                $(".d-table").DataTable().destroy();
                getDatas();
            });

            $("#clear-input").click(function () {
                searchBar.val("");
                $(".d-table").DataTable().destroy();
                getDatas();

            });

            searchBar.change(function () {
                $(".d-table").DataTable().destroy();
                getDatas();
            });
        })
       
    </script>
}