flexbackend.site/Controllers/StaffsController.cs
using Members.dll.Models.Interfaces;
using Members.dll.Models.lnfra.DapperRepositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Members.dll.Models.Services;
using Members.dll.Models.ViewsModels;
using Members.dll.Models.Exts;
using Members.dll.Models.Dtos;
using Members.dll.Models.lnfra;
using System.Web.ModelBinding;
using System.Web.UI.WebControls;
using EFModels.EFModels;
using System.Web.Security;
using Members.dll.Models.ViewsModels.Staff;
using flexbackend.site.Filters;
using static flexbackend.site.Filters.AuthorizeFilter;
using System.Net;
using System.Data.Entity;
using System.Collections;

namespace flexbackend.site.Controllers
{
	public class StaffsController : Controller
	{
		// 控制器，路由和請求處理get、post ; 畫面呈現

		//Create 也要使用這支method但還沒用
		private StaffService GetStaffRepository()
		{
			IStaffRepository repo = new StaffDapperRepository();
			return new StaffService(repo);
		}
		private AppDbContext db = new AppDbContext();

		/// <summary>
		/// 中級的員工權限才可以編輯員工資料
		/// </summary>
		/// <param name="staffId"></param>
		/// <returns></returns>
		[AuthorizeFilter(UserRole.IntermediatePermission)]
		public ActionResult EditStaff(int staffId)
		{
			if (staffId == 0) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			StaffService service = GetStaffRepository();
			var staff = service.GetByStaffId(staffId).ToStaffEditVM();
			
			PrepareCategoryDataSource(0);

			return View(staff);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[AuthorizeFilter(UserRole.IntermediatePermission)]
		public ActionResult EditStaff(EditStaffVM vm)
		{
			PrepareCategoryDataSource(vm.fk_DepartmentId);
			if (ModelState.IsValid == false) return View(vm);
			Result result = ResetStaff(vm);
			if (result.IsSuccess == false)
			{
				ModelState.AddModelError(string.Empty, result.ErrorMessage);
				return View(vm);
			}

			return RedirectToAction("StaffList");
		}

		/// <summary>
		/// 下拉式選單副程式
		/// </summary>
		/// <param name="id"></param>
		private void PrepareCategoryDataSource(int? id)
		{
			var departmentList = db.Departments.ToList();
			departmentList.Insert(0, new Department { DepartmentId = 0, DepartmentName = "請選擇" });

			ViewBag.PermissionsId = new SelectList(db.StaffPermissions, "PermissionsId", "levelName", id);
			ViewBag.DepartmentId = new SelectList(departmentList, "DepartmentId", "DepartmentName", id);
			ViewBag.TitleId = new SelectList(db.JobTitles, "TitleId", "TitleName", id);

			List<SelectListItem> gender = new List<SelectListItem>
			{
			new SelectListItem { Value = "true" , Text = "男" },
			new SelectListItem { Value = "false" , Text = "女" },
			};
			ViewBag.Gender = gender;
		}

		private Result ResetStaff(EditStaffVM vm)
		{
			StaffService service = GetStaffRepository();
			service.ResetStaff(vm.ToStaffEditDto());
			return Result.Success();
		}

		//檢視某筆員工
		public ActionResult GetStaffDetail(int staffId)
		{
			if (staffId == 0)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			StaffService service = GetStaffRepository();
			return View(service.GetStaffDetail(staffId).ToStaffDetailVM());
		}

		
		[AuthorizeFilter(UserRole.AdvancedPermission)]
		public ActionResult DeleteStaff(int staffId)
		{
			//如果staffId為空，返回404錯誤碼
			if (staffId == 0)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			StaffService service = GetStaffRepository();
			service.DeleteStaff(staffId);
			return RedirectToAction("StaffList");
		}

        [AllowAnonymous]
        public ActionResult EditPassword()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult EditPassword(EditPasswordVM vm)
		{
			if (ModelState.IsValid == false) return View(vm);
			Result result = UpdatePassword(vm);

			if (result.IsSuccess == false)
			{
				ModelState.AddModelError(string.Empty, result.ErrorMessage);
				return View(vm);
			}
			return RedirectToAction("Login");
		}

		
		public ActionResult ForgetPassword()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult ForgetPassword(ForgetPasswordVM vm)
		{
			if (ModelState.IsValid == false) return View(vm);

			// 生成email裡的連結
			var urlTemplate = Request.Url.Scheme + "://" +  // 生成 http:.// 或 https://
							 Request.Url.Authority + "/" + // 生成網域名稱或 ip
							 "Staffs/ResetPassword?staffId={0}&confirmCode={1}"; // 生成網頁 url

			Result result = ProcessResetPassword(vm.Account, vm.Email, urlTemplate);

			if (!result.IsSuccess)
			{
				ModelState.AddModelError(string.Empty, result.ErrorMessage);
				return View(vm);
			}			
			return RedirectToAction("ConfirmResetPassword");
		}
        [AllowAnonymous]
        public ActionResult ResetPassword()
		{
			return View();
		}

		[HttpPost]
        [AllowAnonymous]
        public ActionResult ResetPassword(ResetPasswordVM vm, int staffId, string confirmCode)
		{
			if (ModelState.IsValid == false) return View(vm);
			Result result = ProcessChangePassword(staffId, confirmCode, vm.Password);

			if (!result.IsSuccess)
			{
				ModelState.AddModelError(string.Empty, result.ErrorMessage);
				return View(vm);
			}

			return RedirectToAction("Login");
		}
        [AllowAnonymous]
        private Result ProcessChangePassword(int memberId, string confirmCode, string newPassword)
		{
			var db = new AppDbContext();

			// 驗證 memberId, confirmCode是否正確
			var staffInDb = db.Staffs.FirstOrDefault(s => s.StaffId == memberId && s.ConfirmCode == confirmCode);
			if (staffInDb == null) return Result.Fail("找不到對應的會員記錄");

			// 更新密碼,並將 confirmCode清空
			var salt = HashUtility.GetSalt();
			//var encryptedPassword = HashUtility.ToSHA256(newPassword, salt);

			staffInDb.Password = newPassword;
			staffInDb.ConfirmCode = null;

			db.SaveChanges();

			return Result.Success();
		}

        [AllowAnonymous]
        private Result ProcessResetPassword(string account, string email, string urlTemplate)
		{
			var db = new AppDbContext();
			// 檢查account,email正確性
			var staffInDb = db.Staffs.FirstOrDefault(s => s.Account == account);

			if (staffInDb == null) return Result.Fail("帳號或 Email 錯誤"); // 故意不告知確切錯誤原因

			if (string.Compare(email, staffInDb.Email, StringComparison.CurrentCultureIgnoreCase) != 0) return Result.Fail("帳號或 Email 錯誤");

			// 檢查 IsConfirmed必需是true, 因為只有已啟用的帳號才能重設密碼
			if (staffInDb.Account!= account) return Result.Fail("您還沒有啟用本帳號, 請先完成才能重設密碼");

			// 更新記錄, 填入 confirmCode
			var confirmCode = Guid.NewGuid().ToString("N");
			staffInDb.ConfirmCode = confirmCode;
			db.SaveChanges();

			// 發email
			var url = string.Format(urlTemplate, staffInDb.StaffId, confirmCode);
			new EmailHelper().SendForgetPasswordEmail(url, staffInDb.Name, email);

			return Result.Success();
		}

		private Result ResetPassword(ForgetPasswordVM vm)
		{
			StaffService service = GetStaffRepository();
			return service.ResetPassword(vm.ToForgetPasswordDto());
		}

		private Result UpdatePassword(EditPasswordVM vm)
		{
			StaffService service = GetStaffRepository();
			return service.UpdatePassword(vm.ToEditPasswordDto());
		}

		/// <summary>
		/// 沒有權限
		/// </summary>
		/// <returns></returns>
		public ActionResult NoPermission()
		{
			return View();
		}

		public ActionResult Logout()
		{
			Session.Abandon();
			FormsAuthentication.SignOut();
			return Redirect("/Staffs/Login");
		}

        /// <summary>
        /// 登入Get
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult Login()
		{
			return View();
		}

		/// <summary>
		/// 登入POST
		/// </summary>
		/// <param name="vm"></param>
		/// <returns></returns>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[AllowAnonymous]
		public ActionResult Login(LoginVM vm)
		{
			if (ModelState.IsValid == false) return View(vm);

			//對帳號密碼進行驗證
			Result result = ValidLogin(vm);

			//驗證失敗
			if (result.IsSuccess == false)
			{
				ModelState.AddModelError(string.Empty, result.ErrorMessage);
				return View(vm);
			}

			//是否記住登入成功的會員
			const bool remeberMe = false;

			//驗證成功，處理後續登入作業，並將密碼編碼之後加到 Cookie裡面
			(string returnUrl, HttpCookie cookie) processResult = ProcessLogin(vm.Account, remeberMe);
			Response.Cookies.Add(processResult.cookie);

			return Redirect(processResult.returnUrl);
		}

        /// <summary>
        /// 重設密碼通知頁面
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult ConfirmResetPassword()
		{
			return View();
		}

		private (string returnUrl, HttpCookie cookie) ProcessLogin(string account, bool rememberMe)
		{
			var roles = string.Empty; //如用到角色權限就填入

			//建立一張認證票
			var ticket =
				new FormsAuthenticationTicket(
					1,                          //版本別,沒有特別用處
					account,
					DateTime.Now,               //發行日
					DateTime.Now.AddDays(2),    //到期日
					rememberMe,                 //是否續存
					roles,                      //userdata
					"/"                         //cookie位置,通常都放在網站的根目錄
					);

			//將它加密,利用內建的表單認證類別呼叫編碼
			var value = FormsAuthentication.Encrypt(ticket);

			//存入cookie
			var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, value);

			//取得return url
			var url = FormsAuthentication.GetRedirectUrl(account, true); //第二個引數沒有用處

			return (url, cookie);
		}
        [AllowAnonymous]
        private Result ValidLogin(LoginVM vm)
		{
			var db = new AppDbContext();

			//根據帳號去找，並檢查帳號
			var staff = db.Staffs.FirstOrDefault(s => s.Account == vm.Account);
			if (staff == null) return Result.Fail("帳號或密碼有誤");

			//找到帳號，將密碼密碼進行雜湊
			//var salt = HashUtility.GetSalt();
			//var hashPrassword = HashUtility.ToHA256(vm.Password, salt);

			string password = vm.Password;
			Session["UserRole"] = staff.fk_PermissionsId;

			//檢查密碼
			return string.CompareOrdinal(staff.Password, password) == 0
				? Result.Success()
				: Result.Fail("帳號或密碼有誤");
		}

		/// <summary>
		/// 新增員工Get
		/// </summary>

flexbackend.site/Views/Staffs/ConfirmResetPassword.cshtml
@{
    ViewBag.Title = "ConfirmResetPassword";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}


<h2>重設密碼確認信</h2>
請去信箱確認信件，並重設新密碼後重新登入。

flexbackend.site/Views/Staffs/CreateStaff.cshtml
@model Members.dll.Models.ViewsModels.StaffsCreateVM

@{
    ViewBag.Title = "CreateStaff";
    SelectList gender = ViewBag.Gender as SelectList;
}

<h2>新增員工</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="mb-3">
            @Html.LabelFor(model => model.fk_DepartmentId, htmlAttributes: new { @class = "form-label" })
            @Html.DropDownListFor(model => model.fk_DepartmentId, ViewBag.DepartmentId as SelectList, new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.fk_DepartmentId, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.fk_TitleId, htmlAttributes: new { @class = "form-label" })
            @Html.DropDownListFor(model => model.fk_TitleId, ViewBag.TitleId as SelectList, new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.fk_TitleId, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "form-label" })
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "form-label" })
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "form-label" })
            @*<input type="text" class="form-control" name="Birthday" id="Birthday" value="@(Model.Birthday.HasValue?Model.Birthday.Value.ToString("yyyy'/'MM'/'dd"):string.Empty)">*@
            @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.GenderStr, htmlAttributes: new { @class = "form-label" })
            @Html.DropDownListFor(model => model.Gender, gender, new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "form-label" })
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.fk_PermissionsId, htmlAttributes: new { @class = "form-label" })
            @Html.DropDownListFor(model => model.fk_PermissionsId, ViewBag.PermissionsId as SelectList, new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.fk_PermissionsId, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <input type="submit" value="新增" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回會員名單總覽", "StaffList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $("#Birthday").datepicker({ dateFormat: 'yy/mm/dd' });
        })
    </script>
}

flexbackend.site/Views/Staffs/EditPassword.cshtml
@model Members.dll.Models.ViewsModels.Staff.EditPasswordVM

@{
    ViewBag.Title = "EditPassword";
}

<h2>變更密碼</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="row">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="mb-3">
        @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "form-label" })
        @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
    </div>

    <div class="mb-3">
        @Html.LabelFor(model => model.OldPassword, htmlAttributes: new { @class = "form-label" })
        @Html.EditorFor(model => model.OldPassword, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.OldPassword, "", new { @class = "text-danger" })
    </div>

    <div class="mb-3">
        @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "form-label" })
        @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
    </div>

    <div class="mb-3">
        @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "form-label" })
        @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
    </div>

    <div class="mb-3">
        <input type="submit" value="提交" class="btn btn-danger" />
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

flexbackend.site/Views/Staffs/ForgetPassword.cshtml
@model Members.dll.Models.ViewsModels.Staff.ForgetPasswordVM

@{
    ViewBag.Title = "ForgetPassword";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
@section Styles
{
    <style>
        /*#login-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 50vh;
            margin: 50px;
            padding: 80px;
            width: 500px;*/ /*外框寬度*/
        /*height: 400px;*/ /*外框高度*/
        /*background-color: #0B284A; */ /*外框背景*/
        /*border: 1px*/ /*solid #0B284A*/ /*;
            border-radius: 15px;*/ /*外框圓角*/
        /*border-top: 50px solid #BB3E20;*/ /*上面顏色的高度*/
        /*box-shadow: 0 10px 20px rgba(0, 0, 0, 0.3);*/
        /*定位對齊*/
        /*position: relative;
            margin: auto;
            top: 100px;
            text-align: center;
        }

        body {*/
        /*background-color: #3C5067;*/
        /*}

        #useraccount, #email {
            color: #BB3E20;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        #ForgetText {
            display: flex;
            justify-content: center;
            color: black;
            padding-bottom: 10px;
            font-size: larger;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            font-weight: bold;
        }

        .form-control {
            background-color: #ECF1F2;
            border: none;
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.3);
            opacity: 0.5;*/ /* 設定透明度的值 */
        /*}

        .text {
            margin-right: 10px;
            color: #0B284A;
            font-weight: 100;
        }

        #loginImg {
            background-repeat: no-repeat;
            height: 50px;
            object-fit: contain;
            z-index: -1;
        }

        .transparent-image {
            opacity: 0.5;
        }*/
    </style>

    <style>
        #login-container {
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 80px 0;
            width: 500px; /*外框寬度*/
            height: 400px; /*外框高度*/
            /*background-color: #0B284A; */ /*外框背景*/
            border: 3px /*solid #BB3E20*/;
            border-radius: 15px; /*外框圓角*/
            /*border-top: 50px solid #BB3E20;*/ /*上面顏色的高度*/
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.3);
            /*定位對齊*/
            position: absolute;
            margin: auto;
            top: calc((100vh - 400px) / 2);
            left: calc((100% - 500px) / 2 - 150px);
            text-align: center;
            backdrop-filter: blur(6px);
            -webkit-backdrop-filter: blur(6px);
            background: rgba(30,30,50,.7)
        }

        h3 {
            font-size: 40px;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif
        }

        #useraccount, #userpassword {
            color: #BB3E20;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        #loginText {
            color: white;
            padding-bottom: 10px;
            font-size: larger;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            font-weight: bold;
        }

        .form-control {
            background-color: rgba(124,144,167,.7);
            border: none;
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.3);
            font-size: 20px;
            color: black;
            font-weight: bold;
        }

            .form-control:focus {
                background-color: rgba(255,255,255,.5);
                outline:none;
            }

        .text {
            margin-right: 10px;
            color: white;
            font-weight: 100;
            font-size: 19px;
        }

        #loginImg {
            position: fixed;
            top: 0;
            left: 0;
            width: 100vw;
            height: 100vh;
            overflow: hidden;
            object-fit: contain;
            z-index: -1;
        }

        img {
            margin-top: 150px;
            margin-left: 400px;
            width: 1900px;
        }

        .v {
            height: 16px;
            font-weight: bold;
            margin-left: 145px;
        }

        .btn {
            font-size: 20px;
        }
    </style>

}
<div id="loginImg" class="transparent-image">
    <img alt="" src="~/Public/Img/FlexLogo.png" />
</div>

@using (Html.BeginForm())
{

    //@Html.AntiForgeryToken()

    <div id="login-container">
        <div class="row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div id="loginText" class="mb-3">
                <h3>忘記密碼嗎?</h3>
            </div>
            <div class="mt-1" id="useraccount">
                <div class="text"><span class="me-3">帳 號</span></div>
                @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })

            </div>
            <div class="mb-3 text-start v">
                @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
            </div>

            <div id="userpassword">
                <div class="text"><span class="me-3">信 箱</span></div>
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
               
            </div>
            <div class="mb-3 text-start v"> 
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>

            <div class="mt-3">
                <input type="submit" value="確 認" class="btn btn-outline-light" />
                <a href="@Url.Action("Login", "Staffs", new { area = "" })" class="btn btn-outline-light ms-4">返 回 登 入</a>
            </div>
        </div>
    </div>
    
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

flexbackend.site/Views/Staffs/Login.cshtml
@model Members.dll.Models.ViewsModels.LoginVM

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
@section Styles
{
    <style>
        #login-container {
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 80px 0;
            width: 500px; /*外框寬度*/
            height: 400px; /*外框高度*/
            /*background-color: #0B284A; */ /*外框背景*/
            border: 3px /*solid #BB3E20*/;
            border-radius: 15px; /*外框圓角*/
            /*border-top: 50px solid #BB3E20;*/ /*上面顏色的高度*/
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.3);
            /*定位對齊*/
            position: absolute;
            margin: auto;
            top: calc((100vh - 400px) / 2);
            left: calc((100% - 500px) / 2 - 150px);
            text-align: center;
            backdrop-filter: blur(6px);
            -webkit-backdrop-filter: blur(6px);
            background:rgba(30,30,50,.4)
        }

        body {
            background-color: #3C5067;
        }
        h3{
            font-size:40px;
            font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif
        }

        #useraccount, #userpassword {
            color: #BB3E20;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        #loginText {
            color: white;
            padding-bottom: 10px;
            font-size: larger;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            font-weight: bold;
        }

        .form-control {
            background-color:rgba(124,144,167,.7);
            border: none;
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.3);
            font-size:20px;
            color:black;
            font-weight:bold;
        }
            .form-control:focus {
                background-color: rgba(255,255,255,.5);
                outline: none;
            }

            .text {
                margin-right: 10px;
                color: white;
                font-weight: 100;
                font-size: 19px;
            }

        #loginImg {
            position: fixed;
            top: 0;
            left: 0;
            width: 100vw;
            height: 100vh;
            overflow: hidden;
            object-fit: contain;
            z-index: -1;
        }
        img{
            margin-top:150px;
            margin-left:400px;
            width:1900px;
        }
        .verifyText {
            height: 16px;
            font-weight: bold;
            margin-left: 145px;
            
        }
            .verifyText > span {
                color: #ED4656;
            }
            .btn {
                font-size: 20px;
            }
    </style>

}

<div id="loginImg">
    <img alt="" src="~/Public/Img/FlexLogo.png" />
</div>
@using (Html.BeginForm())
{
    @*@Html.AntiForgeryToken()*@ //這個拿掉就可以更換成_LayoutLogin

    <div id="login-container">
        <div class="row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div id="loginText" class="mb-3">
                <h3>LOGIN</h3>
            </div>
            <div class="mt-1" id="useraccount">
                <div class="text"><span class="me-3">帳 號</span></div>
                @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
               
            </div>
            <div class="mb-3 text-start verifyText">
                @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
            </div>

            <div id="userpassword">
                <div class="text"><span class="me-3">密 碼</span></div>
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                
            </div class="mb-3">
            <div class="mb-3 text-start verifyText">@Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })</div>

            <div class="mt-3">
                <input type="submit" value="登 入" class="btn btn-outline-light" />
                <a href="@Url.Action("ForgetPassword", "Staffs", new { area = "" })" class="btn btn-outline-light ms-4">忘 記 密 碼</a>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

flexbackend.site/Views/Staffs/NoPermission.cshtml
@{
    ViewBag.Title = "NoPermission";
}

<h2>權限未經許可</h2>
很抱歉，您無法進入此頁面，請返回重新操作。

<div>
    @Html.ActionLink("返回會員名單總覽", "StaffList")
</div>