flexbackend.site/Controllers/CustomizedShoesPoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Customized_Shoes.dll.Models.Dtos;
using Customized_Shoes.dll.Models.Exts;
using Customized_Shoes.dll.Models.Infra.EFRepository;
using Customized_Shoes.dll.Models.Interface;
using Customized_Shoes.dll.Models.Service;
using Customized_Shoes.dll.Models.ViewModels;
using EFModels.EFModels;
using Flex.Products.dll.Infra.EFRepository;
using Flex.Products.dll.Models.Dtos;
using Flex.Products.dll.Models.ViewModel;
using Flex.Products.dll.Service;

namespace flexbackend.site.Controllers
{
    public class CustomizedShoesPoesController : Controller
    {
        private AppDbContext db = new AppDbContext();
        private IShoesRepository _repo = new CustomizedShoesEFRepository();

        // GET: CustomizedShoesPoes
        public ActionResult Index(ShoesSearchCriteria criteria)
        {
            criteria = criteria ?? new ShoesSearchCriteria();
			PrepareShoesCategoryDataSource(criteria.ShoesCategoryId);

			ViewBag.Criteria = criteria;
            ViewBag.StatusOption = new SelectList(criteria.StatusOption);
            

            var service = new CustomizedShoesService(_repo);
            var shoesproducts = service.IndexshoesPo(criteria).Select(p => p.ToIndexVM());

            if (Request.IsAjaxRequest()) 
            { 
                return Json(shoesproducts);
            }
            return View(shoesproducts);
        }

        [HttpPost]
        public ActionResult EditShoesStatus(List<CustomizedShoesIdAndStatusVM> vm) 
        {
            if (vm != null)
            {
                var dtos = new List<CustomizedShoesDto>();
                foreach (var shoesproduct in vm) 
                {
                    dtos.Add(shoesproduct.ToSaveShoesStatusDto());
                }
                var service = new CustomizedShoesService(_repo);
                var shoesproducts = service.EditShoesStatus(dtos);
                if (shoesproducts.IsSucces)
                {
                    var updatedProducts = service.IndexshoesPo(new ShoesSearchCriteria()).Select(p => p.ToIndexVM());

                    return Json(new { success = true });
                }
            }
            return Json(new { success = false });
        }

		// GET: CustomizedShoesPoes/Details/5
		public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomizedShoesPo customizedShoesPo = db.CustomizedShoesPoes.Find(id);
            if (customizedShoesPo == null)
            {
                return HttpNotFound();
            }
            return View(customizedShoesPo);
        }

        // GET: CustomizedShoesPoes/Create
        public ActionResult Create()
        {
            PrepareShoesCategoryDataSource(null);
            PrepareShoesColorDataSource(null);
            
            var vm = new CustomizedShoesCreateVM();
            return View(vm);
        }

        // POST: CustomizedShoesPoes/Create
        // 若要免於大量指派 (overposting) 攻擊，請啟用您要繫結的特定屬性，
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomizedShoesCreateVM vm)
        {
            PrepareShoesCategoryDataSource(null);
            PrepareShoesColorDataSource(null);
            if(ModelState.IsValid ==  false) return View(vm);

			#region 照片上傳
			var files = Request.Files;
			if (files == null || files.Count == 0)
			{
				ModelState.AddModelError("ImgPaths", "請選擇檔案");
				return View(vm);
			}

			// 設定照片路徑不存在就新增一個
			string path = Server.MapPath("~/Public/Img");
			if (!Directory.Exists(path)) Directory.CreateDirectory(path);

			// 將CreateFile存檔，並取得最後存檔的名稱，副檔名可能不合規格，所以在做一次偵錯
			List<string> saveFileName = SaveFileName(path, files);
			if (saveFileName == null || saveFileName.Count == 0)
			{
				ModelState.AddModelError("ImgPaths", "請選擇檔案");
				return View(vm);
			}

			// 將雜湊後的檔名newFileName加到VM的ImgPaths
			foreach (var fileName in saveFileName)
			{
				vm.ImgPaths.Add(fileName);
			}
            #endregion

            var service = new CustomizedShoesService(_repo);
            var result = service.CreateShoes(vm.ToCreateDto());
            if (result.IsSucces)
            {
                return RedirectToAction("Index");
            }
            else 
            {
                if (result.ErroeMessage.Contains("編碼"))
                {
                    ModelState.AddModelError("ShoesName", result.ErroeMessage);
                }
                return View(vm);
            }
		}

		// GET: CustomizedShoesPoes/Edit/5
		public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var service = new CustomizedShoesService(_repo);
            var shoesproduct = service.GetById((int)id).ToEditVM();

            if (shoesproduct == null) return HttpNotFound();

            PrepareShoesCategoryDataSource(null);
            PrepareShoesColorDataSource(null);

            return View(shoesproduct);
        }

        // POST: CustomizedShoesPoes/Edit/5
        // 若要免於大量指派 (overposting) 攻擊，請啟用您要繫結的特定屬性，
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CustomizedShoesEditVM vm)
        {
            PrepareShoesCategoryDataSource(null);
            PrepareShoesColorDataSource(null);
            if(!ModelState.IsValid) return View(vm);

            var service = new CustomizedShoesService(_repo);
            var result = service.EditShoes(vm.VMToEditDto());
            if (result.IsSucces)
            {
                return RedirectToAction("Index");
            }
            else
            { 
                return View(vm);
            }
        }

        public ActionResult EditImg(int? id)
        {
			if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			var service = new CustomizedShoesService(_repo);
			var product = service.GetImgById((int)id);

			return View(product.ToEditImgVM((int)id));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult EditImg(ShoesEditImgVM vm, List<string> createImgName, List<HttpPostedFileBase> createfile)
		{
			if (vm == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			var service = new CustomizedShoesService(_repo);

			var path = Server.MapPath("~/Public/Img");
			List<ShoesImgDto> editImg = EditShoesImg(path, createImgName, createfile, vm.ShoesProductId);

			if (vm.ShoesPictureUrl == null && createImgName == null)
			{
				var errorVm = service.GetImgById(vm.ShoesProductId);

				ModelState.AddModelError(string.Empty, "至少要有一張照片");

				return View(errorVm.ToEditImgVM(vm.ShoesProductId));
			}

			if (editImg != null && editImg.Count > 0)
			{
				foreach (var img in editImg)
				{
					vm.ShoesPictureUrl.Add(img);
				}
			}

			var product = service.SaveEditImg(vm.VMToEditImgDto());

			if (product.IsSucces)
			{
				return RedirectToAction("Index");
			}
			return View(vm);
		}

		// GET: CustomizedShoesPoes/Delete/5
		public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomizedShoesPo customizedShoesPo = db.CustomizedShoesPoes.Find(id);
            if (customizedShoesPo == null)
            {
                return HttpNotFound();
            }
            return View(customizedShoesPo);
        }

        // POST: CustomizedShoesPoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CustomizedShoesPo customizedShoesPo = db.CustomizedShoesPoes.Find(id);
            db.CustomizedShoesPoes.Remove(customizedShoesPo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

		private void PrepareShoesCategoryDataSource(int? ShoesCategoryId)
		{
            ViewBag.ShoesCategoryId = new SelectList(
                new ShoesCategoryRepository()
                .GetShoesCategory()
                .Prepend(new ShoesCategoryDto { ShoesCategoryId = 0, ShoesCategoryName = "功能分類" }), "ShoesCategoryId", "ShoesCategoryName", ShoesCategoryId);
		}

		private void PrepareShoesColorDataSource(int? ColorId)
		{
			ViewBag.ShoesColor = new SelectList(
				new ShoesColorRepository()
				.GetShoesColorCategory()
				.Prepend(new ShoesColorCategoryDto { ShoesColorId = 0, ColorName = "顏色",ColorCode = "顏色編碼" }), "ShoesColorId", "ColorName", "ColorCode", ColorId);
		}

		/// <summary>
		/// 上傳多張照片
		/// </summary>
		/// <param name="path">照片存放路徑</param>
		/// <param name="files">照片</param>
		/// <returns></returns>
		private List<string> SaveFileName(string path, HttpFileCollectionBase files)
		{
			//沒上傳或是空值，就不處理;
			if (files == null || files.Count == 0) return new List<string>();

			List<string> result = new List<string>();

			//允許的副檔名
			var allowExts = new string[] { ".jpg", ".jpeg", ".png", ".gif", ".tif" };
			for (int i = 0; i < files.Count; i++)
			{
				var file = files[i];

				if (file == null || file.ContentLength == 0 || file.ContentLength > 2 * 1024 * 1024) continue;

				//取得副檔名
				string ext = System.IO.Path.GetExtension(file.FileName);

				//檢查副檔名是否在允許範圍，不允許就不處理
				if (!allowExts.Contains(ext.ToLower())) continue;

				//生成一個新的檔名
				string newFileName = $"{Guid.NewGuid().ToString("N")}{ext}";

flexbackend.site/Views/CustomizedShoesPoes/Create.cshtml
@model Customized_Shoes.dll.Models.ViewModels.CustomizedShoesCreateVM

@{
    ViewBag.Title = "新增基底商品";
    var shoesCategory = ViewBag.ShoesCategoryId as SelectList;
    var colorCategory = ViewBag.ShoesColor as SelectList;
}

<h2>新增基底商品</h2>


@using (Html.BeginForm("Create", "CustomizedShoesPoes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="mb-3">
            @Html.LabelFor(model => model.ShoesName, htmlAttributes: new { @class = "form-label" })
            @Html.EditorFor(model => model.ShoesName, new { htmlAttributes = new { @class = "form-control", placeholder = "鞋種編號" } })
            @Html.ValidationMessageFor(model => model.ShoesName, "", new { @class = "text-danger" })
        </div>
        <div class="col-12">
            <div class="mb-3">
                @Html.LabelFor(model => model.ShoesDescription, htmlAttributes: new { @class = "form-label" })
                @Html.EditorFor(model => model.ShoesDescription, new { htmlAttributes = new { @class = "form-control", placeholder = "商品描述" } })
                @Html.ValidationMessageFor(model => model.ShoesDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="mb-3">
            @Html.LabelFor(model => model.ShoesOrigin, htmlAttributes: new { @class = "form-label" })
            @Html.EditorFor(model => model.ShoesOrigin, new { htmlAttributes = new { @class = "form-control", placeholder = "產地" } })
            @Html.ValidationMessageFor(model => model.ShoesOrigin, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.ShoesUnitPrice, htmlAttributes: new { @class = "form-label" })
            @Html.EditorFor(model => model.ShoesUnitPrice, new { htmlAttributes = new { @class = "form-control", placeholder = "產品售價" } })
            @Html.ValidationMessageFor(model => model.ShoesUnitPrice, "", new { @class = "text-danger" })
        </div>
        <div class="mb-3">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "form-label" })
            <div class="checkbox">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="mb-3">
            @*@Html.LabelFor(model => model.fk_ShoesCategoryId, "fk_ShoesCategoryId", htmlAttributes: new { @class = "form-label" })*@
            <label class="form-label" for="fk_ShoesCategoryId">功能分類</label>
            @Html.DropDownListFor(model => model.fk_ShoesCategoryId, ViewBag.ShoesCategoryId as SelectList, new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.fk_ShoesCategoryId, "", new { @class = "text-danger" })
        </div>
        <div class="mb-3">
            @*@Html.LabelFor(model => model.fk_ShoesColorId, "fk_ShoesColorId", htmlAttributes: new { @class = "form-label" })*@
            <label class="form-label" for="fk_ShoesColorId">主顏色分類</label>
            @Html.DropDownListFor(model => model.fk_ShoesColorId, ViewBag.ShoesColor as SelectList, new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.fk_ShoesColorId, "", new { @class = "text-danger" })
        </div>

        <div id="createImg">
            <div id="previewImages"></div>
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.ImgPaths, htmlAttributes: new { @class = "form-label" })
            <input type="file" name="CreateFile" id="createFile" class="form-control" multiple />
            @Html.ValidationMessageFor(model => model.ImgPaths, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <input id="save" type="submit" value="新增" class="btn btn-primary" />
            <input type="button" value="取消" class="btn btn-primary" onclick='location.href="@Url.Action("Index")"' />
        </div>
    </div>
}

@section Scripts {
    <script>
        $(document).ready(function () {
            checkImg();
        });

        $(document).on('click', '.deleteImgBtn', function () {
            $(this).parent(".img-group").remove();
            updateProductImg();
            updateFileCount();
            clearFileInput();
        });

        function checkImg() {
            var maxSize = 2 * 1024 * 1024;
            $('input[type="file"]').change(function (e) {
                var files = e.target.files;
                if (files && files.length > 0) {
                    $('#previewImages').empty(); // 清空预览区域
                    for (var i = 0; i < files.length; i++) {
                        if (files[i].size < maxSize) {
                            var reader = new FileReader();
                            reader.onload = function (e) {
                                var image = $('<img>');
                                image.attr('src', e.target.result);
                                image.attr('alt', 'Preview');
                                image.css('width', '150px');
                                image.css('height', '150px');

                                var deleteBtn = $('<button>');
                                deleteBtn.attr('type', 'button');
                                deleteBtn.addClass('deleteImgBtn btn btn-danger');
                                deleteBtn.text('删除');

                                var imgGroup = $('<div>');
                                imgGroup.addClass('img-group');
                                imgGroup.append(image);
                                imgGroup.append(deleteBtn);

                                $('#previewImages').append(imgGroup);
                            };
                            reader.readAsDataURL(files[i]);
                        } else {
                            alert("照片超過2MB");
                        }
                    }
                } else {
                    $('#previewImages').empty(); // 清空预览区域
                }
                updateFileCount(); // 更新文件数量
            });
        }

        function updateFileCount() {
            var fileInput = $('#createFile');
            var fileCount = fileInput[0].files.length;
            fileInput.data('count', fileCount); // 使用 data() 方法更新属性值
        }

        function clearFileInput() {
            var fileInput = $('#createFile');
            fileInput.val(''); // 清空文件输入字段的值
            fileInput.wrap('<form>').closest('form').get(0).reset();
            fileInput.unwrap();
        }
    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

flexbackend.site/Views/CustomizedShoesPoes/Delete.cshtml
@model EFModels.EFModels.CustomizedShoesPo

@{
    ViewBag.Title = "刪除產品";
}

<h2>刪除產品</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label class="form-label" for="">鞋種編號</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesName)
        </dd>

        <dt>
            <label class="form-label" for="">商品描述</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesDescription)
        </dd>

        <dt>
            <label class="form-label" for="">產地</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesOrigin)
        </dd>

        <dt>
            <label class="form-label" for="">產品售價</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesUnitPrice)
        </dd>

        <dt>
            <label class="form-label" for="">是否下架</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            <label class="form-label" for="">功能分類</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesCategory.ShoesCategoryName)
        </dd>

        <dt>
            <label class="form-label" for="">顏色分類</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesColorCategory.ColorName)
        </dd>
        <dt>
            <label class="form-label" for="">創建時間</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCreateTime)
        </dd>

        <dt>
            <label class="form-label" for="">編輯時間</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataEditTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="刪除此產品" class="btn btn-danger" /> |
            <div class="btn btn-dark">
                @Html.ActionLink("回到產品管理", "Index")
            </div>
        </div>
    }
</div>

flexbackend.site/Views/CustomizedShoesPoes/Details.cshtml
@model EFModels.EFModels.CustomizedShoesPo

@{
    ViewBag.Title = "商品詳情";
}

<h2>商品詳情</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label class="form-label" for="">鞋種編號</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesName)
        </dd>

        <dt>
            <label class="form-label" for="">商品描述</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesDescription)
        </dd>

        <dt>
            <label class="form-label" for="">產地</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesOrigin)
        </dd>

        <dt>
            <label class="form-label" for="">產品售價</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesUnitPrice)
        </dd>

        <dt>
            <label class="form-label" for="">是否下架</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            <label class="form-label" for="">功能分類</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesCategory.ShoesCategoryName)
        </dd>

        <dt>
            <label class="form-label" for="">顏色分類</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShoesColorCategory.ColorName)
        </dd>
        <dt>
            <label class="form-label" for="">創建時間</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCreateTime)
        </dd>

        <dt>
            <label class="form-label" for="">編輯時間</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataEditTime)
        </dd>

    </dl>
</div>
<p class="btn btn-dark">
    @Html.ActionLink("回到產品管理", "Index")
</p>

flexbackend.site/Views/CustomizedShoesPoes/EditImg.cshtml
@model Customized_Shoes.dll.Models.ViewModels.ShoesEditImgVM

@{
    ViewBag.Title = "編輯商品圖片";
}

<h2>編輯商品圖片</h2>


@using (Html.BeginForm("EditImg", "CustomizedShoesPoes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShoesProductId)

        <div id="editImg" class="border border-3 rounded-2 mb-3">
            <div id="previewImages">
                @for (var i = 0; i < Model.ShoesPictureUrl.Count; i++)
                {
                    <div class="img-group m-2">
                        <img src="~/Public/Img/@Model.ShoesPictureUrl[i].ShoesPictureUrl" style="width:150px;height:150px" />
                        <input type="hidden" name="ShoesPictureUrl[@i].ShoesImgId" value="@Model.ShoesPictureUrl[i].ShoesImgId" />
                        <input type="hidden" name="ShoesPictureUrl[@i].ShoesPictureUrl" value="@Model.ShoesPictureUrl[i].ShoesPictureUrl" />
                        <input type="hidden" name="ShoesPictureUrl[@i].fk_ShoesProductId" value="@Model.ShoesProductId" />
                        <input type="button" value="刪除" class="btn btn-danger ms-3 deleteImgBtn" />
                    </div>
                }
            </div>
            <div id="previewCreateImages">

            </div>
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.ShoesPictureUrl, htmlAttributes: new { @class = "form-label" })
            <input type="file" name="createfile" class="form-control" multiple />
            @Html.ValidationMessageFor(model => model.ShoesPictureUrl, "", new { @class = "text-danger" })
        </div>
        <div class="mb-3">
            <input type="submit" value="確認" class="btn btn-primary" />
            <input type="button" value="取消" class="btn btn-primary" onclick='location.href="@Url.Action("Index")"' />
        </div>
    </div>
}


@section Scripts {
    <script>
        $(document).ready(function () {
            var delBtn = $(".deleteImgBtn");
            //var previewImages = $("#previewImages");

            checkImg();

            delBtn.click(function () {
                $(this).parent(".img-group").remove();
                updateProductImg();
            })
        })

        function updateProductImg() {
            $(".img-group").each(function (index) {
                $(this).find("input[name^='ShoesPictureUrl']").eq(0).attr("name", "ShoesPictureUrl[" + index + "].ShoesImgId");
                $(this).find("input[name^='ShoesPictureUrl']").eq(1).attr("name", "ShoesPictureUrl[" + index + "].ShoesPictureUrl");
                $(this).find("input[name^='ShoesPictureUrl']").eq(2).attr("name", "ShoesPictureUrl[" + index + "].fk_ShoesProductId");
            });
        }
        function updateCreateImgNum() {
            $('.createImg-group').each(function (index) {
                var createImgInput = $(this).find('input[name^="createImgName"]');
                createImgInput.attr("name", "createImgName[" + index + "]");
            })
        }

        function checkImg() {
            var maxSize = 2 * 1024 * 1024;
            $('input[name="createfile"]').change(function (e) {
                var files = e.target.files;
                if (files && files.length > 0) {
                    $('#previewCreateImages').empty();
                    for (let i = 0; i < files.length; i++) {
                        if (files[i].size < maxSize) {
                            var reader = new FileReader();
                            reader.onload = function (e) {

                                var createImgGroup = $('<div class="createImg-group m-2"></div>');
                                var image = $('<img src="' + e.target.result + '" style="width:150px;height:150px" >');
                                var createImgName = $('<input type="hidden" name="createImgName[' + i + ']" value="' + files[i].name + '" />')
                                var deleteBtn = $('<input type="button" value="刪除" class="btn btn-danger ms-3 deleteCreateImgBtn" />');

                                deleteBtn.click(function () {
                                    $(this).parent().remove();
                                    updateCreateImgNum();
                                })

                                createImgGroup.append(image);
                                createImgGroup.append(deleteBtn);
                                createImgGroup.append(createImgName);

                                $('#previewCreateImages').append(createImgGroup);
                            }
                            reader.readAsDataURL(files[i])
                        }
                        else {
                            alert("照片檔案超過2MB");
                        }
                    }
                }
                else {
                    $('#previewCreateImages').empty();
                }
            })
        }
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}